package main

import (
	"bytes"
	"go/format"
	"os"
	"text/template"
)

type operatorSpec struct {
	Const       string
	Func        string
	Implemented bool
}

var operatorSpecs = []operatorSpec{
	{Const: "PLUS", Func: "PlusOp", Implemented: true},
	{Const: "MINUS", Func: "MinusOp", Implemented: true},
	{Const: "EQ", Func: "EqualOp", Implemented: true},
	{Const: "NOT_EQ", Func: "NotEqualOp", Implemented: false},
	{Const: "ASTERISK", Implemented: false},
	{Const: "SLASH", Implemented: false},
	{Const: "FLOOR_DIV", Implemented: false},
	{Const: "PERCENT", Implemented: false},
	{Const: "LT", Implemented: false},
	{Const: "GT", Implemented: false},
}

type templateData struct {
	Implemented []operatorSpec
}

func main() {
	var implemented []operatorSpec
	for _, spec := range operatorSpecs {
		if spec.Implemented {
			implemented = append(implemented, spec)
		}
	}

	tmpl := template.Must(template.New("compile_infix").Parse(`// Code generated by go generate; DO NOT EDIT.

package compile

import (
	"xex/engine"
	"xex/ast/operator"
	"xex/object"
)

func compileInfixExpression(op operator.Operator, valueStack *compileValueStack) (engine.NormalSuffixOperate, specialCase) {
	opends := valueStack.TakeN(2)
	l, r := opends[0], opends[1]
	left, right := l.op, r.op
	lSlotIdx := l.SlotIdx
	rSlotIdx := r.SlotIdx
	lLit := l.specialCase.Lit
	rLit := r.specialCase.Lit

	switch op {
	default:
		panic("not implement")
{{- range .Implemented }}
	case operator.{{ .Const }}:
		if l.IsLocalAndFreeSlot {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if lSlot.Ref != nil {
						if rSlot.Ref != nil {
							return object.{{ .Func }}(lSlot.Ref.Value, rSlot.Ref.Value)
						}
						return object.{{ .Func }}(lSlot.Ref.Value, rSlot.Value)
					}
					if rSlot.Ref != nil {
						return object.{{ .Func }}(lSlot.Value, rSlot.Ref.Value)
					}
					return object.{{ .Func }}(lSlot.Value, rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					if lSlot.Ref != nil {
						return object.{{ .Func }}(lSlot.Ref.Value, rLit)
					}
					return object.{{ .Func }}(lSlot.Value, rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					if lSlot.Ref != nil {
						return object.{{ .Func }}(lSlot.Ref.Value, right(e))
					}
					return object.{{ .Func }}(lSlot.Value, right(e))
				}, specialCase{}
			}
		} else if l.IsLit {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if rSlot.Ref != nil {
						return object.{{ .Func }}(lLit, rSlot.Ref.Value)
					}
					return object.{{ .Func }}(lLit, rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					return object.{{ .Func }}(lLit, rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					return object.{{ .Func }}(lLit, right(e))
				}, specialCase{}
			}
		} else {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if rSlot.Ref != nil {
						return object.{{ .Func }}(left(e), rSlot.Ref.Value)
					}
					return object.{{ .Func }}(left(e), rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					return object.{{ .Func }}(left(e), rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					return object.{{ .Func }}(left(e), right(e))
				}, specialCase{}
			}
		}
{{- end }}
	}

	panic("should not happen")
}
`))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData{Implemented: implemented}); err != nil {
		panic(err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("compile_infix_gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
