package main

import (
	"bytes"
	"go/format"
	"os"
	"text/template"
)

type operatorSpec struct {
	Const       string
	Func        string
	Implemented bool
}

var operatorSpecs = []operatorSpec{
	{Const: "BANG", Func: "BangOp", Implemented: true},
	{Const: "MINUS", Func: "NegateOp", Implemented: true},
}

type templateData struct {
	Implemented []operatorSpec
}

func main() {
	var implemented []operatorSpec
	for _, spec := range operatorSpecs {
		if spec.Implemented {
			implemented = append(implemented, spec)
		}
	}

	tmpl := template.Must(template.New("compile_prefix").Parse(`// Code generated by go generate; DO NOT EDIT.

package compile

import (
	"xex/engine"
	"xex/ast/operator"
	"xex/object"
)

func compilePrefixExpression(op operator.Operator, valueStack *compileValueStack) (engine.NormalSuffixOperate, specialCase) {
	o := valueStack.TakeN(1)[0]
	operand := o.op
	slotIdx := o.SlotIdx

	switch op {
	default:
		panic("not implement")
{{- range .Implemented }}
	case operator.{{ .Const }}:
		if o.IsSpecial && o.IsLocalAndFreeSlot {
			return func(e engine.Env) object.Box {
				slot := e.LocalAndFreeVars[slotIdx]
				if slot.Ref != nil {
					return object.{{ .Func }}(slot.Ref.Value)
				}
				return object.{{ .Func }}(slot.Value)
			}, specialCase{}
		}
		return func(e engine.Env) object.Box {
			return object.{{ .Func }}(operand(e))
		}, specialCase{}
{{- end }}
	}

	panic("should not happen")
}
`))

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateData{Implemented: implemented}); err != nil {
		panic(err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("compile_prefix_gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
