// Code generated by go generate; DO NOT EDIT.

package compile

import (
	"xex/ast/operator"
	"xex/engine"
	"xex/object"
)

func compileInfixExpression(op operator.Operator, valueStack *compileValueStack) (engine.NormalSuffixOperate, specialCase) {
	opends := valueStack.TakeN(2)
	l, r := opends[0], opends[1]
	left, right := l.op, r.op
	lSlotIdx := l.SlotIdx
	rSlotIdx := r.SlotIdx
	lLit := l.specialCase.Lit
	rLit := r.specialCase.Lit

	switch op {
	default:
		panic("not implement")
	case operator.PLUS:
		if l.IsLocalAndFreeSlot {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if lSlot.Ref != nil {
						if rSlot.Ref != nil {
							return object.PlusOp(lSlot.Ref.Value, rSlot.Ref.Value)
						}
						return object.PlusOp(lSlot.Ref.Value, rSlot.Value)
					}
					if rSlot.Ref != nil {
						return object.PlusOp(lSlot.Value, rSlot.Ref.Value)
					}
					return object.PlusOp(lSlot.Value, rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					if lSlot.Ref != nil {
						return object.PlusOp(lSlot.Ref.Value, rLit)
					}
					return object.PlusOp(lSlot.Value, rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					if lSlot.Ref != nil {
						return object.PlusOp(lSlot.Ref.Value, right(e))
					}
					return object.PlusOp(lSlot.Value, right(e))
				}, specialCase{}
			}
		} else if l.IsLit {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if rSlot.Ref != nil {
						return object.PlusOp(lLit, rSlot.Ref.Value)
					}
					return object.PlusOp(lLit, rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					return object.PlusOp(lLit, rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					return object.PlusOp(lLit, right(e))
				}, specialCase{}
			}
		} else {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if rSlot.Ref != nil {
						return object.PlusOp(left(e), rSlot.Ref.Value)
					}
					return object.PlusOp(left(e), rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					return object.PlusOp(left(e), rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					return object.PlusOp(left(e), right(e))
				}, specialCase{}
			}
		}
	case operator.MINUS:
		if l.IsLocalAndFreeSlot {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if lSlot.Ref != nil {
						if rSlot.Ref != nil {
							return object.MinusOp(lSlot.Ref.Value, rSlot.Ref.Value)
						}
						return object.MinusOp(lSlot.Ref.Value, rSlot.Value)
					}
					if rSlot.Ref != nil {
						return object.MinusOp(lSlot.Value, rSlot.Ref.Value)
					}
					return object.MinusOp(lSlot.Value, rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					if lSlot.Ref != nil {
						return object.MinusOp(lSlot.Ref.Value, rLit)
					}
					return object.MinusOp(lSlot.Value, rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					if lSlot.Ref != nil {
						return object.MinusOp(lSlot.Ref.Value, right(e))
					}
					return object.MinusOp(lSlot.Value, right(e))
				}, specialCase{}
			}
		} else if l.IsLit {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if rSlot.Ref != nil {
						return object.MinusOp(lLit, rSlot.Ref.Value)
					}
					return object.MinusOp(lLit, rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					return object.MinusOp(lLit, rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					return object.MinusOp(lLit, right(e))
				}, specialCase{}
			}
		} else {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if rSlot.Ref != nil {
						return object.MinusOp(left(e), rSlot.Ref.Value)
					}
					return object.MinusOp(left(e), rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					return object.MinusOp(left(e), rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					return object.MinusOp(left(e), right(e))
				}, specialCase{}
			}
		}
	case operator.EQ:
		if l.IsLocalAndFreeSlot {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if lSlot.Ref != nil {
						if rSlot.Ref != nil {
							return object.EqualOp(lSlot.Ref.Value, rSlot.Ref.Value)
						}
						return object.EqualOp(lSlot.Ref.Value, rSlot.Value)
					}
					if rSlot.Ref != nil {
						return object.EqualOp(lSlot.Value, rSlot.Ref.Value)
					}
					return object.EqualOp(lSlot.Value, rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					if lSlot.Ref != nil {
						return object.EqualOp(lSlot.Ref.Value, rLit)
					}
					return object.EqualOp(lSlot.Value, rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					lSlot := e.LocalAndFreeVars[lSlotIdx]
					if lSlot.Ref != nil {
						return object.EqualOp(lSlot.Ref.Value, right(e))
					}
					return object.EqualOp(lSlot.Value, right(e))
				}, specialCase{}
			}
		} else if l.IsLit {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if rSlot.Ref != nil {
						return object.EqualOp(lLit, rSlot.Ref.Value)
					}
					return object.EqualOp(lLit, rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					return object.EqualOp(lLit, rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					return object.EqualOp(lLit, right(e))
				}, specialCase{}
			}
		} else {
			if r.IsLocalAndFreeSlot {
				return func(e engine.Env) object.Box {
					rSlot := e.LocalAndFreeVars[rSlotIdx]
					if rSlot.Ref != nil {
						return object.EqualOp(left(e), rSlot.Ref.Value)
					}
					return object.EqualOp(left(e), rSlot.Value)
				}, specialCase{}
			} else if r.IsLit {
				return func(e engine.Env) object.Box {
					return object.EqualOp(left(e), rLit)
				}, specialCase{}
			} else {
				return func(e engine.Env) object.Box {
					return object.EqualOp(left(e), right(e))
				}, specialCase{}
			}
		}
	}

	panic("should not happen")
}
