// Code generated by go generate; DO NOT EDIT.

package compile

import (
	"xex/ast/operator"
	"xex/engine"
	"xex/object"
)

func compilePrefixExpression(op operator.Operator, valueStack *compileValueStack) (engine.NormalSuffixOperate, specialCase) {
	o := valueStack.TakeN(1)[0]
	operand := o.op
	slotIdx := o.SlotIdx

	switch op {
	default:
		panic("not implement")
	case operator.BANG:
		if o.IsSpecial && o.IsLocalAndFreeSlot {
			return func(e engine.Env) object.Box {
				slot := e.LocalAndFreeVars[slotIdx]
				if slot.Ref != nil {
					return object.BangOp(slot.Ref.Value)
				}
				return object.BangOp(slot.Value)
			}, specialCase{}
		}
		return func(e engine.Env) object.Box {
			return object.BangOp(operand(e))
		}, specialCase{}
	case operator.MINUS:
		if o.IsSpecial && o.IsLocalAndFreeSlot {
			return func(e engine.Env) object.Box {
				slot := e.LocalAndFreeVars[slotIdx]
				if slot.Ref != nil {
					return object.NegateOp(slot.Ref.Value)
				}
				return object.NegateOp(slot.Value)
			}, specialCase{}
		}
		return func(e engine.Env) object.Box {
			return object.NegateOp(operand(e))
		}, specialCase{}
	}

	panic("should not happen")
}
